import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import "./globals.css";
import { Poppins } from "@next/font/google";

export const metadata = {
  title: "Paris Exchange",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
